name: "CI"
on:
  push:
    branches:
      - master
      - staging
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Load database
        run: |
          ls -hal
          pwd
          sleep 5

