name: "CI"
on:
  push:
    branches:
      - master
      - staging
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Testingg
        run: |
          ls -hal
          pwd
          sleep 5
          cat readme.md
          echo "conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "ref: ${{ github.ref }}"
          echo "head_branch: ${{ github.event.workflow_run.head_branch }}"
